import { POST } from '@/app/api/generate/export/route';
import { requireAuthenticatedUser } from '@/lib/auth';

jest.mock('@/lib/auth', () => ({
  requireAuthenticatedUser: jest.fn(),
}));

describe('generated document editable export route', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  it('exports edited generated content as a PDF generated by PDFKit', async () => {
    jest.mocked(requireAuthenticatedUser).mockResolvedValue({
      user: { id: 'user-1' },
    } as Awaited<ReturnType<typeof requireAuthenticatedUser>>);

    const response = await POST(
      new Request('http://localhost/api/generate/export', {
        method: 'POST',
        body: JSON.stringify({
          title: 'CV cible',
          content: 'Profil modifié avant téléchargement',
          format: 'pdf',
        }),
      }),
    );
    const bytes = Buffer.from(await response.arrayBuffer());

    expect(response.status).toBe(200);
    expect(response.headers.get('content-type')).toBe('application/pdf');
    expect(response.headers.get('content-disposition')).toContain('cv-cible.pdf');
    expect(bytes.subarray(0, 5).toString('latin1')).toBe('%PDF-');
    expect(bytes.toString('latin1')).toContain('/Producer');
    expect(bytes.toString('latin1')).toContain('(PDFKit)');
  });
});
